package values

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/pmezard/go-difflib/difflib"
	"gopkg.in/yaml.v3"

	"github.com/helmetica-framework/transmuter/pkg/mix"
)

// DefaultOutput is where a reagent keeps the values its expressions compute,
// beside the helm-unittest suites that read them.
const DefaultOutput = "test/unit/computed-values.yaml"

// header explains the file to whoever opens it and, unlike the hand-written
// file it replaces, says how to bring it back in line.
const header = "# Generated by `transmuter values`. Do not edit.\n" +
	"#\n" +
	"# Regenerate with `transmuter values`. `transmuter values --check` fails when it is stale.\n" +
	"\n"

// Options configures one generation or check.
type Options struct {
	Path      string
	Name      string
	Namespace string
	Output    string
	Check     bool
}

// Values writes the computed values of the reagent at opts.Path, or with
// opts.Check compares them against what is already on disk and fails when the
// two have drifted apart.
func Values(opts Options) error {
	if opts.Path == "" {
		opts.Path = "."
	}
	if opts.Namespace == "" {
		opts.Namespace = "default"
	}
	if opts.Output == "" {
		opts.Output = DefaultOutput
	}

	loaded, err := mix.LoadChartAs(opts.Path, opts.Name, opts.Namespace)
	if err != nil {
		return fmt.Errorf("cel pre-processing: %w", err)
	}

	vals, err := computed(loaded.Chart.Values, loaded.Pvalues)
	if err != nil {
		return err
	}

	want, err := render(vals)
	if err != nil {
		return err
	}

	target := opts.Output
	if !filepath.IsAbs(target) {
		target = filepath.Join(opts.Path, target)
	}

	if opts.Check {
		return check(target, want)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, want, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}

	slog.Info("computed values written", "reagent", loaded.Chart.Name(), "path", target)

	return nil
}

// check compares what is on disk at target with want, and fails with a diff
// when they differ. It never writes: a check that repairs what it is checking
// would pass on the run that should have failed.
func check(target string, want []byte) error {
	have, err := os.ReadFile(target)
	if errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("%s is missing, run `transmuter values` to write it", target)
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", target, err)
	}

	if bytes.Equal(have, want) {
		return nil
	}

	diff, err := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        difflib.SplitLines(string(have)),
		B:        difflib.SplitLines(string(want)),
		FromFile: target,
		ToFile:   "computed now",
		Context:  3,
	})
	if err != nil {
		return fmt.Errorf("diffing %s: %w", target, err)
	}

	return fmt.Errorf("%s no longer matches the cel: expressions, run `transmuter values` to regenerate it:\n%s", target, diff)
}

// render returns the file content: the generated header followed by the
// computed values as YAML.
func render(values map[string]any) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	if err := enc.Encode(values); err != nil {
		return nil, fmt.Errorf("encoding computed values: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("encoding computed values: %w", err)
	}

	return buf.Bytes(), nil
}
