package values

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// writeChart lays out a chart directory from a map of relative path to content.
func writeChart(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for rel, content := range files {
		path := filepath.Join(dir, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}
	return dir
}

// body returns the YAML below the generated header.
func body(t *testing.T, content string) string {
	t.Helper()
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if line != "" && !strings.HasPrefix(line, "#") {
			return strings.Join(lines[i:], "\n")
		}
	}
	return ""
}

const probeChartYaml = `apiVersion: v2
name: probe
type: application
version: 0.1.0
`

const exprValues = `service:
  replicas: 3
  storage: 10Gi
sub:
  replicas: "cel: values.service.replicas"
  size: "cel: values.service.storage"
  ha: "cel: values.service.replicas > 1"
`

func TestValuesWritesTheComputedSubset(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)
	content := string(written)

	assert.True(t, strings.HasPrefix(content, "# Generated by"), "the file must carry the generated header")
	assert.Contains(t, content, "--check", "the header must say how to catch drift")
	assert.NotContains(t, content, "service:", "only the computed paths belong in the file")

	assert.Equal(t, "sub:\n  ha: true\n  replicas: 3\n  size: 10Gi\n", body(t, content))
}

func TestValuesWithoutExpressions(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": "service:\n  replicas: 3\n",
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)

	assert.Equal(t, "{}\n", body(t, string(written)), "a reagent with no expressions still gets a usable values file")
}

func TestValuesUsesTheClaim(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": "who: \"cel: claim.name\"\nwhere: \"cel: claim.namespace\"\n",
	})

	require.NoError(t, Values(Options{Path: dir, Name: "instance", Namespace: "prod"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)

	assert.Equal(t, "where: prod\nwho: instance\n", body(t, string(written)))
}

func TestValuesHonoursOutput(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default", Output: "test/fixtures/generated.yaml"}))

	assert.FileExists(t, filepath.Join(dir, "test", "fixtures", "generated.yaml"))
	assert.NoFileExists(t, filepath.Join(dir, DefaultOutput))
}

func TestValuesIsDeterministic(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})
	out := filepath.Join(dir, DefaultOutput)

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))
	first, err := os.ReadFile(out)
	require.NoError(t, err)

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))
	second, err := os.ReadFile(out)
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second))
}

func TestValuesCheck(t *testing.T) {
	tests := []struct {
		name        string
		mutate      func(t *testing.T, dir, out string)
		errContains string // empty means the check passes
	}{
		{
			name:   "freshly generated file passes",
			mutate: func(*testing.T, string, string) {},
		},
		{
			name: "edited file fails and names the offending key",
			mutate: func(t *testing.T, _, out string) {
				require.NoError(t, os.WriteFile(out, []byte("sub:\n  replicas: 99\n"), 0o644))
			},
			errContains: "replicas",
		},
		{
			name: "missing file fails",
			mutate: func(t *testing.T, _, out string) {
				require.NoError(t, os.Remove(out))
			},
			errContains: "computed-values.yaml",
		},
		{
			name: "expression changed since the file was written",
			mutate: func(t *testing.T, dir, _ string) {
				changed := strings.Replace(exprValues, "values.service.replicas > 1", "values.service.replicas > 99", 1)
				require.NoError(t, os.WriteFile(filepath.Join(dir, "values.yaml"), []byte(changed), 0o644))
			},
			errContains: "ha",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeChart(t, map[string]string{
				"Chart.yaml":  probeChartYaml,
				"values.yaml": exprValues,
			})
			out := filepath.Join(dir, DefaultOutput)
			require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

			tt.mutate(t, dir, out)

			err := Values(Options{Path: dir, Namespace: "default", Check: true})
			if tt.errContains == "" {
				assert.NoError(t, err)
				return
			}
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.errContains)
			assert.Contains(t, err.Error(), "transmuter values", "the error must say how to fix it")
		})
	}
}

func TestValuesCheckNeverWrites(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	err := Values(Options{Path: dir, Namespace: "default", Check: true})

	require.Error(t, err)
	assert.NoFileExists(t, filepath.Join(dir, DefaultOutput), "--check must never create the file it is checking")
}

const overridableValues = `service:
  replicas: 1
  storage: 10Gi
sub:
  replicas: "cel: values.service.replicas"
  size: "cel: values.service.storage"
`

// writeOverride puts a value file beside the chart and returns its path.
func writeOverride(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	return path
}

func TestValuesWithValueFiles(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": overridableValues,
	})
	override := writeOverride(t, dir, "ha.yaml", "service:\n  replicas: 3\n")

	require.NoError(t, Values(Options{Path: dir, Namespace: "default", ValueFiles: []string{override}}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)
	content := string(written)

	body := content[strings.Index(content, "sub:"):]
	assert.Equal(t, "sub:\n  replicas: 3\n  size: 10Gi\n", body, "the value file reaches the expressions, the chart defaults fill the rest")
	assert.NotContains(t, content, "service:", "a value file's own keys are not computed values")
}

func TestValuesExpressionBeatsAValueFile(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": overridableValues,
	})
	override := writeOverride(t, dir, "wrong.yaml", "sub:\n  replicas: 99\n")

	require.NoError(t, Values(Options{Path: dir, Namespace: "default", ValueFiles: []string{override}}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)
	body := string(written)[strings.Index(string(written), "sub:"):]

	// celvalues writes its results last, so an expression path is not overridable.
	// The cluster behaves the same way, and the fixture has to say so.
	assert.Contains(t, body, "replicas: 1")
	assert.NotContains(t, body, "99")
}

func TestValuesValueFileBlockingAnExpression(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": overridableValues,
	})
	override := writeOverride(t, dir, "blocked.yaml", "sub: not-a-map\n")

	err := Values(Options{Path: dir, Namespace: "default", ValueFiles: []string{override}})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "sub.replicas", "the error has to name the path that cannot be written")
}

func TestValuesHeaderRecordsTheCommand(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": overridableValues,
	})
	writeOverride(t, dir, "ha.yaml", "service:\n  replicas: 3\n")

	// value files resolve against the working directory, the way helm -f does
	t.Chdir(dir)

	require.NoError(t, Values(Options{Name: "instance", Namespace: "default", ValueFiles: []string{"ha.yaml"}}))

	written, err := os.ReadFile(DefaultOutput)
	require.NoError(t, err)
	assert.Contains(t, string(written), "transmuter values --name instance -f ha.yaml",
		"the header has to carry the flags that shaped the file")
}

func TestValuesCheckIncludesTheValueFiles(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": overridableValues,
	})
	override := writeOverride(t, dir, "ha.yaml", "service:\n  replicas: 3\n")
	with := Options{Path: dir, Namespace: "default", ValueFiles: []string{override}}

	require.NoError(t, Values(with))

	without := Options{Path: dir, Namespace: "default", Check: true}
	require.Error(t, Values(without), "a check that drops the value files is checking a different question")

	with.Check = true
	assert.NoError(t, Values(with))
}
