package values

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// writeChart lays out a chart directory from a map of relative path to content.
func writeChart(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for rel, content := range files {
		path := filepath.Join(dir, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}
	return dir
}

// body returns the YAML below the generated header.
func body(t *testing.T, content string) string {
	t.Helper()
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if line != "" && !strings.HasPrefix(line, "#") {
			return strings.Join(lines[i:], "\n")
		}
	}
	return ""
}

const probeChartYaml = `apiVersion: v2
name: probe
type: application
version: 0.1.0
`

const exprValues = `service:
  replicas: 3
  storage: 10Gi
sub:
  replicas: "cel: values.service.replicas"
  size: "cel: values.service.storage"
  ha: "cel: values.service.replicas > 1"
`

func TestValuesWritesTheComputedSubset(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)
	content := string(written)

	assert.True(t, strings.HasPrefix(content, "# Generated by"), "the file must carry the generated header")
	assert.Contains(t, content, "transmuter values --check", "the header must say how to catch drift")
	assert.NotContains(t, content, "service:", "only the computed paths belong in the file")

	assert.Equal(t, "sub:\n  ha: true\n  replicas: 3\n  size: 10Gi\n", body(t, content))
}

func TestValuesWithoutExpressions(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": "service:\n  replicas: 3\n",
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)

	assert.Equal(t, "{}\n", body(t, string(written)), "a reagent with no expressions still gets a usable values file")
}

func TestValuesUsesTheClaim(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": "who: \"cel: claim.name\"\nwhere: \"cel: claim.namespace\"\n",
	})

	require.NoError(t, Values(Options{Path: dir, Name: "instance", Namespace: "prod"}))

	written, err := os.ReadFile(filepath.Join(dir, DefaultOutput))
	require.NoError(t, err)

	assert.Equal(t, "where: prod\nwho: instance\n", body(t, string(written)))
}

func TestValuesHonoursOutput(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	require.NoError(t, Values(Options{Path: dir, Namespace: "default", Output: "test/fixtures/generated.yaml"}))

	assert.FileExists(t, filepath.Join(dir, "test", "fixtures", "generated.yaml"))
	assert.NoFileExists(t, filepath.Join(dir, DefaultOutput))
}

func TestValuesIsDeterministic(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})
	out := filepath.Join(dir, DefaultOutput)

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))
	first, err := os.ReadFile(out)
	require.NoError(t, err)

	require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))
	second, err := os.ReadFile(out)
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second))
}

func TestValuesCheck(t *testing.T) {
	tests := []struct {
		name        string
		mutate      func(t *testing.T, dir, out string)
		errContains string // empty means the check passes
	}{
		{
			name:   "freshly generated file passes",
			mutate: func(*testing.T, string, string) {},
		},
		{
			name: "edited file fails and names the offending key",
			mutate: func(t *testing.T, _, out string) {
				require.NoError(t, os.WriteFile(out, []byte("sub:\n  replicas: 99\n"), 0o644))
			},
			errContains: "replicas",
		},
		{
			name: "missing file fails",
			mutate: func(t *testing.T, _, out string) {
				require.NoError(t, os.Remove(out))
			},
			errContains: "computed-values.yaml",
		},
		{
			name: "expression changed since the file was written",
			mutate: func(t *testing.T, dir, _ string) {
				changed := strings.Replace(exprValues, "values.service.replicas > 1", "values.service.replicas > 99", 1)
				require.NoError(t, os.WriteFile(filepath.Join(dir, "values.yaml"), []byte(changed), 0o644))
			},
			errContains: "ha",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeChart(t, map[string]string{
				"Chart.yaml":  probeChartYaml,
				"values.yaml": exprValues,
			})
			out := filepath.Join(dir, DefaultOutput)
			require.NoError(t, Values(Options{Path: dir, Namespace: "default"}))

			tt.mutate(t, dir, out)

			err := Values(Options{Path: dir, Namespace: "default", Check: true})
			if tt.errContains == "" {
				assert.NoError(t, err)
				return
			}
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.errContains)
			assert.Contains(t, err.Error(), "transmuter values", "the error must say how to fix it")
		})
	}
}

func TestValuesCheckNeverWrites(t *testing.T) {
	dir := writeChart(t, map[string]string{
		"Chart.yaml":  probeChartYaml,
		"values.yaml": exprValues,
	})

	err := Values(Options{Path: dir, Namespace: "default", Check: true})

	require.Error(t, err)
	assert.NoFileExists(t, filepath.Join(dir, DefaultOutput), "--check must never create the file it is checking")
}
